- id: conda-env-sorter
  name: Sort dependencies in conda environment files.
  entry: conda-env-sorter
  language: python
  files: environment
  types: [yaml]
- id: no-print-statements
  name: Disallow print statements
  entry: no-print-statements
  language: python
  types: [python]
- id: check-execution-order
  name: Check cells were executed sequentially
  entry: check-execution-order
  language: python
  types: [jupyter]
- id: check-test-naming
  name: Check test names start with 'test'
  entry: check-test-naming
  language: python
  types: [python]
