repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.9.3
    hooks:
      - id: validate_manifest
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude: ^README\.md$
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        files: ^(madforhooks|tests)/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        files: ^madforhooks/
        exclude: /__init__\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        files: \.(py|rst|md)$
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.15.1
    hooks:
      - id: setup-cfg-fmt
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
