[tool.isort]
profile = "black"

[tool.coverage.run]
source = ["madforhooks"]

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
ignore_errors = true
omit = [
  "tests/*",
]

[tool.pylint.messages_control]
disable = [
  "C0330", # to work well with `black`
  "E0401", # Unable to import '_pytest.capture' (this is just for typing anyway)
  "E1136", # Value 'Optional' is unsubscriptable (bug? https://github.com/PyCQA/pylint/issues/3882)
]
