name: Dispatch pre-commit

on:
  # TODO(kszucs): support pull_request_review_comment
  issue_comment:
    types:
      - created
      - edited

jobs:
  autotune:
    name: "Fix all the things"
    if: startsWith(github.event.comment.body, '@github-actions autotune')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.TOKEN }}
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pre-commit-dispatched-${{ runner.os }}-build
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install-pre-commit
        run: python -m pip install --upgrade pre-commit
      - name: Slash Command Dispatch
        run: pre-commit run --all-files || (exit 0)
      - name: Commit results
        run: |
          git config user.name "$(git log -1 --pretty=format:%an)"
          git config user.email "$(git log -1 --pretty=format:%ae)"
          git commit -a -m 'Autoformat/render all the things [automated commit]' || echo "No changes to commit"
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.TOKEN }}
